### ISSUE TITLE
Feature Request | Show clearly where files are saved

### ISSUE THREAD

**Issue by wayneoutthere** [fredldotme/screenrecorder-ubports#11]
nice app!
One problem: I just did a screen recording and accidentally recorded some very sensitive data and wish to delete this recording but... I can't find it.  I thought it would be saved in the video gallery but it wasn't there.  I then went to look for settings in app to find out where it saves the files, but there weren't any settings to change in the app.

Therefore:
Feature request: _Somewhere obvious, show clearly where the saved files will be located._

Thanks!

**Comment by fredldotme** [comment]
Saved files are stored in a temporary location, only referenced until the next recording starts. Hence it makes no sense to add further caution for the use of the app since they're deleted once shared with another app via Content-Hub or canceled.

**Comment by wayneoutthere** [comment]
Great to know now... but I didn't know that.  
Do other users know this intuitively?  
Every other screen recorder I've used saves to video directory or something similar.
Is it possible others might not know that and go through what I went through?

**Comment by fredldotme** [comment]
The only thing I am going to say to this is: Don't expect assassins around every corner, there might be none.
