### ISSUE TITLE
Create destination folder for recordings during app install or first start

### ISSUE THREAD

**Issue by wilfridd** [fredldotme/screenrecorder-ubports#2]
-  Issue : start the app, click "start recording" > app crashes with journal log :

writing to file 24
QFileDevice::seek: IODevice is not open
QIODevice::write (QFile, "/home/phablet/.local/share/screenrecorder.ubports/screen_recording_2023_12_23__17_21_09_536.mp4"): device not open

- workaround : 
mkdir /home/phablet/.local/share/screenrecorder.ubports 

thanks
w.

**Comment by fredldotme** [comment]
Handled by: 07e68ba
