### ISSUE TITLE
Records the built-in display when connected to an external display

### ISSUE THREAD

**Issue by kugiigi** [fredldotme/screenrecorder-ubports#8]
### Steps to Reproduce
1. Connect phone to an external display
2. Open screen recorder and start a recording

### Expected Results
The desktop and the external display is recorded.

### Actual Results
The built-in display is recorded so it's just the virtual touchpad.

**Comment by fredldotme** [comment]
Could you please try building this branch with `clickable` and report back?

https://github.com/fredldotme/screenrecorder-ubports/tree/secondary-monitor

**Comment by kugiigi** [comment]
This is what I got.

https://github.com/fredldotme/screenrecorder-ubports/assets/29456786/5f1dceee-becc-4c1f-aeba-2f0d0a4b8158

**Comment by fredldotme** [comment]
Please try again with the same branch.
